### ISSUE TITLE
Created a variant where the AI doesn't do pitstops and try-catch'd an exception during practice

### ISSUE THREAD

**Issue by strajk-** [Pixelatedza/MMAE#2]
[Assembly-CSharp.zip](https://github.com/user-attachments/files/16971496/Assembly-CSharp.zip)

Decided to remove Pitstops from the AI decisions, had countless of races where the AI made the dumb decision of pitting 1-2 laps before the end, falling back to the back of the grid, everything is still automated except for pitstops which have to be controlled by the user.
Maybe add this one as a third variant of the dll?

SetInputsForVehicle might cause an exception if for some ungodly reason one of the drivers returns null, causing the game to crash during practice, just wrapped it in a try-catch, works, below a small video showing the crash and the fix.

https://github.com/user-attachments/assets/7baf0048-fe37-49b9-bc5e-2aedacc631ce

**Comment by Pixelatedza** [comment]
Hey, happy to add as a variant, your also welcome to raise a PR. Is this with or without perfect setup?

**Comment by Pixelatedza** [comment]
Added to variants in 9a04ff2
